### ISSUE TITLE
Not able to unpack sample

### ISSUE THREAD

**Issue by xk0m1** [eybisi/kavanoz#13]
kavanoz 41b9a5f1a347465d4471f89f37c621d4946266c113a20411eac49c915522e5f4.apk
✸ Extracting apk/dex informationTraceback (most recent call last):
  File "env/bin/kavanoz", line 8, in <module>
    sys.exit(cli())
  File "env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "env/lib/python3.10/site-packages/kavanoz/core.py", line 82, in cli
    k = Kavanoz(filename, output_dir=output_dir)
  File "env/lib/python3.10/site-packages/kavanoz/core.py", line 36, in __init__
    self.plugins = [
  File "env/lib/python3.10/site-packages/kavanoz/core.py", line 36, in <listcomp>
    self.plugins = [
  File "env/lib/python3.10/site-packages/kavanoz/plugin_loader.py", line 64, in get_plugins
    yield import_plugin(plugin)
  File "env/lib/python3.10/site-packages/kavanoz/plugin_loader.py", line 31, in import_plugin
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "frozen importlib._bootstrap_external>", line 879, in exec_module
  File "frozen importlib._bootstrap_external>", line 1017, in get_code
  File "frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "env/lib/python3.10/site-packages/kavanoz/loader/coper.py", line 313
    self.logger.debug(f"RC4 encrypted file name : {stack_data[i+1].decode("utf-8")}")
                                                                           ^^^
SyntaxError: f-string: unmatched '('

**Comment by eybisi** [comment]
which python and kavanoz version you are using? Im getting unpacked file with kavanoz 0.0.4
```
λ kavanoz 41b9a5f1a347465d4471f89f37c621d4946266c113a20411eac49c915522e5f4
✨ Unpacked successfully!
Plugin tag : loader.rc4.v1
Plugin description : Unpacker rc4 based variants
Output file : ./external-d9416c04.dex
```
```
✗ pip show kavanoz
Name: kavanoz
Version: 0.0.4
```

**Comment by xk0m1** [comment]
i am also using kavanoz 0.0.4 
i am guessing something is wrong with my sample
