### ISSUE TITLE
type object is not subscriptable error

### ISSUE THREAD

**Issue by cryptax** [eybisi/kavanoz#3]
I get this error when I try kavanoz. Do you have an idea why?
I installed kavanoz in its virtual environment, then did `pip install -e .`
I am running Python 3.8.17. I can try another more recent version if that's the issue.

```
kavanoz ~/samples/bch/BCH_Cash2.apk 
Traceback (most recent call last):
  File "/home/axelle/softs/kavanoz/kavanoz-venv/bin/kavanoz", line 5, in <module>
    from kavanoz.core import cli
  File "/home/axelle/softs/kavanoz/src/kavanoz/core.py", line 3, in <module>
    from kavanoz.unpack_plugin import Unpacker
  File "/home/axelle/softs/kavanoz/src/kavanoz/unpack_plugin.py", line 13, in <module>
    class Unpacker:
  File "/home/axelle/softs/kavanoz/src/kavanoz/unpack_plugin.py", line 19, in Unpacker
    self, tag: str, name: str, apk_object: APK, dvms: list[DalvikVMFormat], output_dir
TypeError: 'type' object is not subscriptable
```

**Comment by eybisi** [comment]
Try to run with python3.9 and above

**Comment by cryptax** [comment]
Excellent! It worked just perfectly! I used Python 3.10.12 which was already installed in another pyenv.

```
$ kavanoz ./BCH_Cash2.apk 
✨ Unpacked succesfully!
Plugin tag : loader.rc4.v1 
Plugin description : Unpacker rc4 based variants 
Output file : ./external-2485e963.dex 
```

Even greater, your tool automatically works out the RC4 key :)
