### ISSUE TITLE
Malformed ZIP: This is not a DEX file! Wrong endian tag: '0x0000006c

### ISSUE THREAD

**Issue by cryptax** [eybisi/kavanoz#9]
Get sample SHA256: `46553a5db767a8b570e9d11bfe39e4817839daa534f2b5cedf54b72b2e735478`.
In assets, it embeds `child.apk` (SHA256: `ba69178e065c3bc762e3c0066edcb6fcf48cad558e78eb2da4913a03d8244e87`) which is malformed. The sample is packed with JsonPacker that Kavanoz would normally unpack without issues, but due to the ZIP, it breaks.

NB. The sample is Android/SpyNote malware.

```
$ kavanoz child.apk 
✹ Extracting apk/dex informationTraceback (most recent call last):
  File "/home/axelle/softs/myvirtualenvs/kavanoz-venv/bin/kavanoz", line 8, in <module>
    sys.exit(cli())
  File "/home/axelle/softs/myvirtualenvs/kavanoz-venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/axelle/softs/myvirtualenvs/kavanoz-venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/axelle/softs/myvirtualenvs/kavanoz-venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/axelle/softs/myvirtualenvs/kavanoz-venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/axelle/softs/myvirtualenvs/kavanoz-venv/lib/python3.10/site-packages/kavanoz/core.py", line 82, in cli
    k = Kavanoz(filename, output_dir=output_dir)
  File "/home/axelle/softs/myvirtualenvs/kavanoz-venv/lib/python3.10/site-packages/kavanoz/core.py", line 44, in __init__
    self.dexes = [DEX(dex) for dex in self.apk_object.get_all_dex()]
  File "/home/axelle/softs/myvirtualenvs/kavanoz-venv/lib/python3.10/site-packages/kavanoz/core.py", line 44, in <listcomp>
    self.dexes = [DEX(dex) for dex in self.apk_object.get_all_dex()]
  File "/home/axelle/softs/myvirtualenvs/kavanoz-venv/lib/python3.10/site-packages/androguard/core/dex/__init__.py", line 7669, in __init__
    self._load(buff)
  File "/home/axelle/softs/myvirtualenvs/kavanoz-venv/lib/python3.10/site-packages/androguard/core/dex/__init__.py", line 7675, in _load
    self.header = HeaderItem(0, self.raw, self.CM)
  File "/home/axelle/softs/myvirtualenvs/kavanoz-venv/lib/python3.10/site-packages/androguard/core/dex/__init__.py", line 483, in __init__
    cm.packer = DalvikPacker(self.endian_tag)
  File "/home/axelle/softs/myvirtualenvs/kavanoz-venv/lib/python3.10/site-packages/androguard/core/dex/__init__.py", line 7617, in __init__
    raise ValueError("This is not a DEX file! Wrong endian tag: '0x{:08x}'".format(endian_tag))
ValueError: This is not a DEX file! Wrong endian tag: '0x0000006c'
```

**Comment by erev0s** [comment]
@cryptax could you please share the apk to test it out?

**Comment by cryptax** [comment]
@erev0s can't you get it from virustotal: https://www.virustotal.com/gui/file/ba69178e065c3bc762e3c0066edcb6fcf48cad558e78eb2da4913a03d8244e87 ?

**Comment by erev0s** [comment]
hi @cryptax , no as far as I know as a normal user i do not have that option. But no worries I found that apk. Thanks for getting back to me in any case.

**Comment by cryptax** [comment]
@erev0s wonderful that you got it :)
